export default {
  entryPagePath: 'pages/walletModal/index',
  pages: [
    'pages/index/index',
    'pages/web-view/index',
    'pages/button/index',
    'pages/box/index',
    'pages/buttonMenu/index',
    'pages/text/index',
    'pages/heading/index',
    'pages/checkbox/index',
    'pages/input/index',
    'pages/link/index',
    'pages/notificationDot/index',
    'pages/message/index',
    'pages/icon/index',
    'pages/toggle/index',
    'pages/tag/index',
    'pages/skeleton/index',
    'pages/spinner/index',
    'pages/pancakeToggle/index',
    'pages/overlay/index',
    'pages/modal/index',
    'pages/themeSwitcher/index',
    'pages/walletModal/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Binance',
    navigationBarTextStyle: 'black',
  },
}
